export default [
  { id: 1, name: 'Address book', icon: '\uf2b9' },
  { id: 2, name: 'Address card', icon: '\uf2bb' },
  { id: 3, name: 'Anchor', icon: '\uf13d' },
  { id: 4, name: 'Apple Whole', icon: '\uf5d1' },
  { id: 5, name: 'Atom', icon: '\uf5d2' },
  { id: 6, name: 'Award', icon: '\uf559' },
  { id: 7, name: 'Baby', icon: '\uf77c' },
  { id: 8, name: 'Bacon', icon: '\uf7e5' },
  { id: 9, name: 'Balance Scale', icon: '\uf24e' },
  { id: 10, name: 'Bank', icon: '\uf19c' },
  { id: 11, name: 'Battery Full', icon: '\uf240' },
  { id: 12, name: 'Beer', icon: '\uf0fc' },
  { id: 13, name: 'Bell', icon: '\uf0f3' },
  { id: 14, name: 'Bell slash', icon: '\uf1f6' },
  { id: 15, name: 'Bicycle', icon: '\uf206' },
  { id: 16, name: 'Binoculars', icon: '\uf1e5' },
  { id: 17, name: 'Birthday Cake', icon: '\uf1fd' },
  { id: 18, name: 'Blender', icon: '\uf517' },
  { id: 19, name: 'Bolt', icon: '\uf0e7' },
  { id: 20, name: 'Bomb', icon: '\uf1e2' },
  { id: 21, name: 'Bone', icon: '\uf5d7' },
  { id: 22, name: 'Book', icon: '\uf02d' },
  { id: 23, name: 'Bookmark', icon: '\uf02e' },
  { id: 24, name: 'Bowling Ball', icon: '\uf436' },
  { id: 25, name: 'Box', icon: '\uf466' },
  { id: 26, name: 'Brain', icon: '\uf5dc' },
  { id: 27, name: 'Bread Slice', icon: '\uf7ec' },
  { id: 28, name: 'Briefcase', icon: '\uf0b1' },
  { id: 29, name: 'Bug', icon: '\uf188' },
  { id: 30, name: 'Building', icon: '\uf1ad' },
  { id: 31, name: 'Bus', icon: '\uf207' },
  { id: 32, name: 'Calculator', icon: '\uf1ec' },
  { id: 33, name: 'Calendar', icon: '\uf133' },
  { id: 34, name: 'Calendar check', icon: '\uf274' },
  { id: 35, name: 'Calendar days', icon: '\uf073' },
  { id: 36, name: 'Calendar minus', icon: '\uf272' },
  { id: 37, name: 'Calendar plus', icon: '\uf271' },
  { id: 38, name: 'Calendar xmark', icon: '\uf273' },
  { id: 39, name: 'Camera', icon: '\uf030' },
  { id: 40, name: 'Candy Cane', icon: '\uf786' },
  { id: 41, name: 'Car', icon: '\uf1b9' },
  { id: 42, name: 'Cat', icon: '\uf6be' },
  { id: 43, name: 'Chair', icon: '\uf6c0' },
  { id: 44, name: 'Charging Station', icon: '\uf5e7' },
  { id: 45, name: 'Chart bar', icon: '\uf080' },
  { id: 46, name: 'Chess', icon: '\uf439' },
  { id: 47, name: 'Chess bishop', icon: '\uf43a' },
  { id: 48, name: 'Chess king', icon: '\uf43f' },
  { id: 49, name: 'Chess knight', icon: '\uf441' },
  { id: 50, name: 'Chess pawn', icon: '\uf443' },
  { id: 51, name: 'Chess queen', icon: '\uf445' },
  { id: 52, name: 'Chess rook', icon: '\uf447' },
  { id: 53, name: 'Church', icon: '\uf51d' },
  { id: 54, name: 'Circle', icon: '\uf111' },
  { id: 55, name: 'Circle check', icon: '\uf058' },
  { id: 56, name: 'Circle dot', icon: '\uf192' },
  { id: 57, name: 'Circle down', icon: '\uf358' },
  { id: 58, name: 'Circle left', icon: '\uf359' },
  { id: 59, name: 'Circle pause', icon: '\uf28b' },
  { id: 60, name: 'Circle play', icon: '\uf144' },
  { id: 61, name: 'Circle question', icon: '\uf059' },
  { id: 62, name: 'Circle right', icon: '\uf35a' },
  { id: 63, name: 'Circle stop', icon: '\uf28d' },
  { id: 64, name: 'Circle up', icon: '\uf35b' },
  { id: 65, name: 'Circle user', icon: '\uf2bd' },
  { id: 66, name: 'Circle xmark', icon: '\uf057' },
  { id: 67, name: 'Clipboard', icon: '\uf328' },
  { id: 68, name: 'Clock', icon: '\uf017' },
  { id: 69, name: 'Clone', icon: '\uf24d' },
  { id: 70, name: 'Closed captioning', icon: '\uf20a' },
  { id: 71, name: 'Cloud', icon: '\uf0c2' },
  { id: 72, name: 'Cloud download', icon: '\uf0ed' },
  { id: 73, name: 'Cloud upload', icon: '\uf0ee' },
  { id: 74, name: 'Comment', icon: '\uf075' },
  { id: 75, name: 'Comment dots', icon: '\uf4ad' },
  { id: 76, name: 'Comments', icon: '\uf086' },
  { id: 77, name: 'Compass', icon: '\uf14e' },
  { id: 78, name: 'Copyright', icon: '\uf1f9' },
  { id: 79, name: 'Copy', icon: '\uf0c5' },
  { id: 80, name: 'Credit card', icon: '\uf09d' },
  { id: 81, name: 'Envelope', icon: '\uf0e0' },
  { id: 82, name: 'Envelope open', icon: '\uf2b6' },
  { id: 83, name: 'Eye', icon: '\uf06e' },
  { id: 84, name: 'Eye slash', icon: '\uf070' },
  { id: 85, name: 'Face angry', icon: '\uf556' },
  { id: 86, name: 'Face dizzy', icon: '\uf567' },
  { id: 87, name: 'Face flushed', icon: '\uf579' },
  { id: 88, name: 'Face frown', icon: '\uf119' },
  { id: 89, name: 'Face frown open', icon: '\uf57a' },
  { id: 90, name: 'Face grimace', icon: '\uf57f' },
  { id: 91, name: 'Face grin', icon: '\uf580' },
  { id: 92, name: 'Face grin beam', icon: '\uf582' },
  { id: 93, name: 'Face grin beam sweat', icon: '\uf583' },
  { id: 94, name: 'Face grin hearts', icon: '\uf584' },
  { id: 95, name: 'Face grin squint', icon: '\uf585' },
  { id: 96, name: 'Face grin squint tears', icon: '\uf586' },
  { id: 97, name: 'Face grin stars', icon: '\uf587' },
  { id: 98, name: 'Face grin tongue', icon: '\uf589' },
  { id: 99, name: 'Face grin tongue squint', icon: '\uf58a' },
  { id: 100, name: 'Face grin tongue wink', icon: '\uf58b' },
  { id: 101, name: 'Face grin wide', icon: '\uf581' },
  { id: 102, name: 'Face grin wink', icon: '\uf58c' },
  { id: 103, name: 'Face kiss', icon: '\uf596' },
  { id: 104, name: 'Face kiss beam', icon: '\uf597' },
  { id: 105, name: 'Face kiss wink heart', icon: '\uf598' },
  { id: 106, name: 'Face laugh', icon: '\uf599' },
  { id: 107, name: 'Face laugh beam', icon: '\uf59a' },
  { id: 108, name: 'Face laugh squint', icon: '\uf59b' },
  { id: 109, name: 'Face laugh wink', icon: '\uf59c' },
  { id: 110, name: 'Face meh', icon: '\uf11a' },
  { id: 111, name: 'Face meh blank', icon: '\uf5a4' },
  { id: 112, name: 'Face rolling eyes', icon: '\uf5a5' },
  { id: 113, name: 'Face sad cry', icon: '\uf5b3' },
  { id: 114, name: 'Face sad tear', icon: '\uf5b4' },
  { id: 115, name: 'Face smile', icon: '\uf118' },
  { id: 116, name: 'Face smile beam', icon: '\uf5b8' },
  { id: 117, name: 'Face smile wink', icon: '\uf4da' },
  { id: 118, name: 'Face surprise', icon: '\uf5c2' },
  { id: 119, name: 'Face tired', icon: '\uf5c8' },
  { id: 120, name: 'File', icon: '\uf15b' },
  { id: 121, name: 'File audio', icon: '\uf1c7' },
  { id: 122, name: 'File code', icon: '\uf1c9' },
  { id: 123, name: 'File excel', icon: '\uf1c3' },
  { id: 124, name: 'File image', icon: '\uf1c5' },
  { id: 125, name: 'File lines', icon: '\uf15c' },
  { id: 126, name: 'File pdf', icon: '\uf1c1' },
  { id: 127, name: 'File powerpoint', icon: '\uf1c4' },
  { id: 128, name: 'File video', icon: '\uf1c8' },
  { id: 129, name: 'File word', icon: '\uf1c2' },
  { id: 130, name: 'File zipper', icon: '\uf1c6' },
  { id: 131, name: 'Flag', icon: '\uf024' },
  { id: 132, name: 'Flask', icon: '\uf0c3' },
  { id: 133, name: 'Floppy disk', icon: '\uf0c7' },
  { id: 134, name: 'Folder', icon: '\uf07b' },
  { id: 135, name: 'Folder closed', icon: '\uf07b' },
  { id: 136, name: 'Folder open', icon: '\uf07c' },
  { id: 137, name: 'Font awesome', icon: '\uf2b4' },
  { id: 138, name: 'Futbol', icon: '\uf1e3' },
  { id: 139, name: 'Gem', icon: '\uf3a5' },
  { id: 140, name: 'Hand', icon: '\uf256' },
  { id: 141, name: 'Hand back fist', icon: '\uf255' },
  { id: 142, name: 'Hand lizard', icon: '\uf258' },
  { id: 143, name: 'Hand peace', icon: '\uf25b' },
  { id: 144, name: 'Hand point down', icon: '\uf0a7' },
  { id: 145, name: 'Hand point left', icon: '\uf0a5' },
  { id: 146, name: 'Hand point right', icon: '\uf0a4' },
  { id: 147, name: 'Hand point up', icon: '\uf0a6' },
  { id: 148, name: 'Hand pointer', icon: '\uf25a' },
  { id: 149, name: 'Hand rock', icon: '\uf255' },
  { id: 150, name: 'Hand scissors', icon: '\uf257' },
  { id: 151, name: 'Handshake', icon: '\uf2b5' },
  { id: 152, name: 'Hard drive', icon: '\uf0a0' },
  { id: 153, name: 'Heart', icon: '\uf004' },
  { id: 154, name: 'Hospital', icon: '\uf0f8' },
  { id: 155, name: 'Hourglass', icon: '\uf254' },
  { id: 156, name: 'Hourglass half', icon: '\uf252' },
  { id: 157, name: 'Id badge', icon: '\uf2c1' },
  { id: 158, name: 'Id card', icon: '\uf2c2' },
  { id: 159, name: 'Image', icon: '\uf03e' },
  { id: 160, name: 'Images', icon: '\uf302' },
  { id: 161, name: 'Keyboard', icon: '\uf11c' },
  { id: 162, name: 'Lemon', icon: '\uf094' },
  { id: 163, name: 'Life ring', icon: '\uf1cd' },
  { id: 164, name: 'Lightbulb', icon: '\uf0eb' },
  { id: 165, name: 'Map', icon: '\uf279' },
  { id: 166, name: 'Message', icon: '\uf27a' },
  { id: 167, name: 'Money bill 1', icon: '\uf3d1' },
  { id: 168, name: 'Moon', icon: '\uf186' },
  { id: 169, name: 'Music', icon: '\uf001' },
  { id: 170, name: 'Newspaper', icon: '\uf1ea' },
  { id: 171, name: 'Note sticky', icon: '\uf249' },
  { id: 172, name: 'Object group', icon: '\uf247' },
  { id: 173, name: 'Object ungroup', icon: '\uf248' },
  { id: 174, name: 'Paper plane', icon: '\uf1d8' },
  { id: 175, name: 'Paste', icon: '\uf0ea' },
  { id: 176, name: 'Pen to square', icon: '\uf044' },
  { id: 177, name: 'Phone', icon: '\uf095' },
  { id: 178, name: 'Phone flip', icon: '\uf879' },
  { id: 179, name: 'Phone slash', icon: '\uf3dd' },
  { id: 180, name: 'Procedures', icon: '\uf487' },
  { id: 181, name: 'Rectangle list', icon: '\uf022' },
  { id: 182, name: 'Rectangle xmark', icon: '\uf410' },
  { id: 183, name: 'Registered', icon: '\uf25d' },
  { id: 184, name: 'Share from square', icon: '\uf14d' },
  { id: 185, name: 'Snowflake', icon: '\uf2dc' },
  { id: 186, name: 'Square', icon: '\uf0c8' },
  { id: 187, name: 'Square caret down', icon: '\uf150' },
  { id: 188, name: 'Square caret left', icon: '\uf191' },
  { id: 189, name: 'Square caret right', icon: '\uf152' },
  { id: 190, name: 'Square caret up', icon: '\uf151' },
  { id: 191, name: 'Square check', icon: '\uf14a' },
  { id: 192, name: 'Square full', icon: '\uf45c' },
  { id: 193, name: 'Square minus', icon: '\uf146' },
  { id: 194, name: 'Square plus', icon: '\uf0fe' },
  { id: 195, name: 'Star', icon: '\uf005' },
  { id: 196, name: 'Star half', icon: '\uf089' },
  { id: 197, name: 'Star half stroke', icon: '\uf5c0' },
  { id: 198, name: 'Sun', icon: '\uf185' },
  { id: 199, name: 'Thumbs down', icon: '\uf165' },
  { id: 200, name: 'Thumbs up', icon: '\uf164' },
  { id: 201, name: 'Trash can', icon: '\uf2ed' },
  { id: 202, name: 'User', icon: '\uf007' },
  { id: 203, name: 'Window maximize', icon: '\uf2d0' },
  { id: 204, name: 'Window minimize', icon: '\uf2d1' },
  { id: 205, name: 'Window restore', icon: '\uf2d2' },
  { id: 206, name: 'Yin Yang', icon: '\uf6ad' },
];
