import { Data } from './data.interface';

export const MOCKEDDATA: Data = {
  dataId: '1234',
  nodes: [
    {
      id: '123',
      label: ['John Doe', '01/01/1970'],
      imageUrl: 'https://randomuser.me/api/portraits/thumb/men/24.jpg',
      fx: 1000,
      fy: 400,
      additionalIcon: '\uf3a5',
    },
    {
      id: '456',
      label: ['Richard Hill', '14/05/1982'],
      imageUrl: 'https://randomuser.me/api/portraits/thumb/men/99.jpg',
      fx: 332,
      fy: 684,
      additionalIcon: '',
    },
    {
      id: '789',
      label: ['Rick Smith', 'Software Developer'],
      imageUrl: 'https://randomuser.me/api/portraits/thumb/men/21.jpg',
      fx: 55,
      fy: 60,
      additionalIcon: '\uf2dc',
    },
    {
      id: '4',
      label: ['James Jones', 'BA'],
      imageUrl: 'https://randomuser.me/api/portraits/thumb/men/9.jpg',
      fx: 414,
      fy: 369,
      additionalIcon: '',
    },
    {
      id: '423',
      label: ['Aston Villa', 'Football Club', 'Founded 1874'],
      imageUrl: 'https://houseofv.ghost.io/content/images/2024/01/GC72JKwWwAAuyGk.png',
      fx: 313,
      fy: 255,
      additionalIcon: '\uf1e3',
    },
  ],
  links: [
    {
      source: '123',
      target: '456',
      label: ['Worked at IBM', 'Both in same scrum team'],
      lineStyle: 'Dotted',
      sourceArrow: false,
      targetArrow: true,
      linkId: '123_456',
      relationships: [
        {
          linkIndex: 0,
          label: 'Worked at IBM',
          lineStyle: 'Dotted',
          source: '123',
          sourceArrow: false,
          target: '456',
          targetArrow: true,
          linkIcon: true,
        },
        {
          linkIndex: 1,
          label: 'Both in same scrum team',
          lineStyle: 'Solid',
          source: '123',
          sourceArrow: true,
          target: '456',
          targetArrow: false,
          linkIcon: true,
        },
      ],
    },
    {
      source: '456',
      target: '789',
      label: [
        'Play in the same football team',
        'Daughters in the same class at school',
        'Went on a family holiday together last year',
      ],
      lineStyle: 'Solid',
      sourceArrow: true,
      targetArrow: true,
      linkId: '456_789',
      relationships: [
        {
          linkIndex: 2,
          label: 'Play in the same football team',
          lineStyle: 'Solid',
          source: '456',
          sourceArrow: false,
          target: '789',
          targetArrow: true,
          linkIcon: false,
        },
        {
          linkIndex: 3,
          label: 'Daughters in the same class at school',
          lineStyle: 'Solid',
          source: '456',
          sourceArrow: true,
          target: '789',
          targetArrow: false,
          linkIcon: true,
        },
        {
          linkIndex: 4,
          label: 'Went on a family holiday together last year',
          lineStyle: 'Solid',
          source: '456',
          sourceArrow: true,
          target: '789',
          targetArrow: false,
          linkIcon: false,
        },
      ],
    },
    {
      source: '789',
      target: '123',
      label: ['Drink in the same pub', 'Drinking friends'],
      lineStyle: 'Dotted',
      sourceArrow: true,
      targetArrow: true,
      linkId: '789_123',
      relationships: [
        {
          linkIndex: 5,
          label: 'Drink in the same pub',
          lineStyle: 'Dotted',
          source: '789',
          sourceArrow: false,
          target: '123',
          targetArrow: true,
          linkIcon: true,
        },
        {
          linkIndex: 6,
          label: 'Drinking friends',
          lineStyle: 'Dotted',
          source: '789',
          sourceArrow: true,
          target: '123',
          targetArrow: false,
          linkIcon: false,
        },
      ],
    },
    {
      source: '4',
      target: '123',
      label: ['Same University'],
      lineStyle: 'Dotted',
      sourceArrow: true,
      targetArrow: false,
      linkId: '4_123',
      relationships: [
        {
          linkIndex: 7,
          label: ['Same University'],
          lineStyle: 'Dotted',
          source: '4',
          sourceArrow: false,
          target: '123',
          targetArrow: false,
          linkIcon: true,
        },
      ],
    },
  ],
};

export const NEWDATA: Data = {
  dataId: '1234',
  nodes: [
    {
      id: '123',
      label: ['John Doe', '01/01/1970'],
      imageUrl: 'https://randomuser.me/api/portraits/thumb/men/24.jpg',
      fx: 100,
      fy: 400,
      additionalIcon: '',
    },
    {
      id: '456',
      label: ['Richard Hill', '14/05/1982'],
      imageUrl: 'https://randomuser.me/api/portraits/thumb/men/99.jpg',
      fx: 410,
      fy: 284,
      additionalIcon: '',
    },
    {
      id: '789',
      label: ['Rick Smith', 'Software Developer'],
      imageUrl: 'https://randomuser.me/api/portraits/thumb/men/21.jpg',
      fx: 55,
      fy: 60,
      additionalIcon: '',
    },
    {
      id: '101112',
      label: ['Jane Doe', '13/09/1970'],
      imageUrl: 'https://randomuser.me/api/portraits/thumb/women/3.jpg',
      fx: null,
      fy: null,
      additionalIcon: '',
    },
    {
      id: '131415',
      label: ['Rebecca Jones', 'Doctor'],
      imageUrl: 'https://randomuser.me/api/portraits/thumb/women/66.jpg',
      fx: null,
      fy: null,
      additionalIcon: '',
    },
  ],
  links: [
    {
      source: '123',
      target: '456',
      label: ['Worked at IBM', 'Both in same scrum team'],
      lineStyle: 'Dotted',
      sourceArrow: false,
      targetArrow: true,
      linkId: '123_456',
      relationships: [
        {
          linkIndex: 0,
          label: 'Worked at IBM',
          lineStyle: 'Dotted',
          source: '123',
          sourceArrow: false,
          target: '456',
          targetArrow: true,
          linkIcon: false,
        },
        {
          linkIndex: 1,
          label: 'Both in same scrum team',
          lineStyle: 'Solid',
          source: '123',
          sourceArrow: true,
          target: '456',
          targetArrow: false,
          linkIcon: false,
        },
      ],
    },
    {
      source: '456',
      target: '789',
      label: [
        'Play in the same football team',
        'Daughters in the same class at school',
        'Went on a family holiday together last year',
      ],
      lineStyle: 'Solid',
      sourceArrow: true,
      targetArrow: true,
      linkId: '456_789',
      relationships: [
        {
          linkIndex: 2,
          label: 'Play in the same football team',
          lineStyle: 'Solid',
          source: '456',
          sourceArrow: false,
          target: '789',
          targetArrow: true,
          linkIcon: false,
        },
        {
          linkIndex: 3,
          label: 'Daughters in the same class at school',
          lineStyle: 'Solid',
          source: '456',
          sourceArrow: true,
          target: '789',
          targetArrow: false,
          linkIcon: false,
        },
        {
          linkIndex: 4,
          label: 'Went on a family holiday together last year',
          lineStyle: 'Solid',
          source: '456',
          sourceArrow: true,
          target: '789',
          targetArrow: false,
          linkIcon: false,
        },
      ],
    },
    {
      source: '789',
      target: '123',
      label: ['Drink in the same pub', 'Drinking friends'],
      lineStyle: 'Dotted',
      sourceArrow: true,
      targetArrow: true,
      linkId: '789_123',
      relationships: [
        {
          linkIndex: 5,
          label: 'Drink in the same pub',
          lineStyle: 'Dotted',
          source: '789',
          sourceArrow: false,
          target: '123',
          targetArrow: true,
          linkIcon: false,
        },
        {
          linkIndex: 6,
          label: 'Drinking friends',
          lineStyle: 'Dotted',
          source: '789',
          sourceArrow: true,
          target: '123',
          targetArrow: false,
          linkIcon: false,
        },
      ],
    },
    {
      source: '123',
      target: '101112',
      label: ['Married'],
      lineStyle: 'Solid',
      sourceArrow: true,
      targetArrow: true,
      linkId: '123_101112',
      relationships: [
        {
          linkIndex: 7,
          label: 'Married',
          lineStyle: 'Dotted',
          source: '123',
          sourceArrow: true,
          target: '101112',
          targetArrow: true,
          linkIcon: false,
        },
      ],
    },
  ],
};
