import { Data } from './data.interface';

export const mockedData: Data = {
  irUrn: '1234',
  nodes: [
    {
      id: '123',
      version: 0,
      typeName: 'men',
      label: ['John Doe', '01/01/1970'],
      icon: '21',
      xpos: 0,
      ypos: 0,
      x: 0,
      y: 0,
      fx: 1000,
      fy: 400,
      attachedToAuthorisedIRs: true,
      attachedToUnauthorisedIRs: true,
    },
    {
      id: '456',
      version: 0,
      typeName: 'men',
      label: ['Richard Hill', '14/05/1982'],
      icon: '44',
      xpos: 0,
      ypos: 0,
      x: 0,
      y: 0,
      fx: 410,
      fy: 284,
      attachedToAuthorisedIRs: true,
      attachedToUnauthorisedIRs: false,
    },
    {
      id: '789',
      version: 0,
      typeName: 'men',
      label: ['Rick Smith', 'Software Developer'],
      icon: '99',
      xpos: 0,
      ypos: 0,
      x: 0,
      y: 0,
      fx: 55,
      fy: 60,
      attachedToAuthorisedIRs: true,
      attachedToUnauthorisedIRs: true,
    },
    {
      id: '4',
      version: 0,
      typeName: 'men',
      label: ['James Jones', 'BA'],
      icon: '9',
      xpos: 0,
      ypos: 0,
      x: 0,
      y: 0,
      fx: null,
      fy: null,
      attachedToAuthorisedIRs: false,
      attachedToUnauthorisedIRs: false,
    },
    {
      id: '423',
      version: 0,
      typeName: 'women',
      label: ['Linda Jones', 'Pilot'],
      icon: '9',
      xpos: 0,
      ypos: 0,
      x: 0,
      y: 0,
      fx: null,
      fy: null,
      attachedToAuthorisedIRs: false,
      attachedToUnauthorisedIRs: false,
    },
  ],
  links: [
    {
      source: '123',
      target: '456',
      label: ['Worked at IBM', 'Both in same scrum team'],
      lineStyle: 'Unconfirmed',
      sourceArrow: false,
      targetArrow: true,
      linkId: '123',
      relationships: [
        {
          label: 'Worked at IBM',
          lineStyle: 'Unconfirmed',
          source: '123',
          sourceArrow: false,
          target: '456',
          targetArrow: true,
          attachedToAuthorisedIRs: true,
          attachedToUnauthorisedIRs: true,
        },
        {
          label: 'Both in same scrum team',
          lineStyle: 'Confirmed',
          source: '123',
          sourceArrow: true,
          target: '456',
          targetArrow: false,
          attachedToAuthorisedIRs: true,
          attachedToUnauthorisedIRs: true,
        },
      ],
    },
    {
      source: '456',
      target: '789',
      label: [
        'Play in the same football team',
        'Daughters in the same class at school',
        'Went on a family holiday together last year',
      ],
      lineStyle: 'Confirmed',
      sourceArrow: true,
      targetArrow: true,
      linkId: '456',
      relationships: [
        {
          label: 'Play in the same football team',
          lineStyle: 'Confirmed',
          source: '456',
          sourceArrow: false,
          target: '789',
          targetArrow: true,
          attachedToAuthorisedIRs: true,
          attachedToUnauthorisedIRs: false,
        },
        {
          label: 'Daughters in the same class at school',
          lineStyle: 'Confirmed',
          source: '456',
          sourceArrow: true,
          target: '789',
          targetArrow: false,
          attachedToAuthorisedIRs: false,
          attachedToUnauthorisedIRs: false,
        },
        {
          label: 'Went on a family holiday together last year',
          lineStyle: 'Confirmed',
          source: '456',
          sourceArrow: true,
          target: '789',
          targetArrow: false,
          attachedToAuthorisedIRs: true,
          attachedToUnauthorisedIRs: false,
        },
      ],
    },
    {
      source: '789',
      target: '123',
      label: ['Drink in the same pub', 'Drinking friends'],
      lineStyle: 'Unconfirmed',
      sourceArrow: true,
      targetArrow: true,
      linkId: '789',
      relationships: [
        {
          label: 'Drink in the same pub',
          lineStyle: 'Unconfirmed',
          source: '789',
          sourceArrow: false,
          target: '123',
          targetArrow: true,
          attachedToAuthorisedIRs: true,
          attachedToUnauthorisedIRs: false,
        },
        {
          label: 'Drinking friends',
          lineStyle: 'Unconfirmed',
          source: '789',
          sourceArrow: true,
          target: '123',
          targetArrow: false,
          attachedToAuthorisedIRs: true,
          attachedToUnauthorisedIRs: false,
        },
      ],
    },
    {
      source: '4',
      target: '123',
      label: ['Same University'],
      lineStyle: 'Unconfirmed',
      sourceArrow: true,
      targetArrow: false,
      linkId: '4',
      relationships: [
        {
          label: ['Same University'],
          lineStyle: 'Unconfirmed',
          source: '4',
          sourceArrow: false,
          target: '123',
          targetArrow: false,
          attachedToAuthorisedIRs: true,
          attachedToUnauthorisedIRs: true,
        },
      ],
    },
  ],
};
